import { GoogleGenAI, Type } from "@google/genai";
import { ForensicReport, Verdict, ModelScore } from '../types';

// Initialize Gemini API client
// Note: API Key is injected via process.env.API_KEY as per best practices
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Converts a File object to a Base64 string.
 */
const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
        const base64String = reader.result.split(',')[1];
        resolve(base64String);
      } else {
        reject(new Error("Failed to convert file to base64"));
      }
    };
    reader.onerror = (error) => reject(error);
  });
};

export const analyzeImage = async (file: File): Promise<ForensicReport> => {
  const startTime = performance.now();
  
  try {
    const base64Data = await fileToBase64(file);

    // Using gemini-3-flash-preview for better quota management and lower latency
    const model = "gemini-3-flash-preview";

    const prompt = `
    You are a senior forensic image analyst and computer vision expert. Your task is to detect if the provided image is REAL (authentic photography) or FAKE (AI-generated by GANs/Diffusion models like Midjourney, Stable Diffusion, Flux, or digitally manipulated via Photoshop).

    Conduct a deep forensic analysis focusing on:
    1. **Spatial & Anatomical Consistency**: Look for unnatural skin textures (plastic/glossy), asymmetrical eyes/ears, strange hands/fingers, hair blending into background, and inconsistent accessories (glasses, jewelry).
    2. **Lighting & Physics**: Analyze shadows, reflections in eyes (corneal specularity), and consistent light sources.
    3. **Frequency & Noise**: Detect smooth patches typical of denoising, inconsistent sensor noise (ISO grain), or checkerboard artifacts from GAN upsampling.
    4. **Context & Semantics**: Look for background logic errors, warping, or alien text.

    If the image is clearly a cartoon, drawing, or painting, mark it as REAL (as in "authentic artwork") unless it claims to be a photo, but note the style. However, if it looks like AI art, mark it as FAKE.

    Return the result strictly as JSON matching the specified schema.
    Generate 'modelScores' for exactly these 4 categories to simulate a multi-model ensemble: 
    'EfficientNet-B7 (Spatial)', 'XceptionNet (Mesoscopic)', 'ViT-Base (Global)', 'Frequency (DFT/DCT)'.
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          { inlineData: { mimeType: file.type, data: base64Data } },
          { text: prompt }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            verdict: { type: Type.STRING, enum: ["REAL", "FAKE", "SUSPICIOUS"] },
            confidence: { type: Type.NUMBER, description: "0-100 score. Higher means more certain in the verdict." },
            explanation: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING }, 
              description: "3-5 bullet points explaining the forensic findings." 
            },
            artifacts: {
              type: Type.OBJECT,
              properties: {
                spatialInconsistencies: { type: Type.NUMBER, description: "0-100 severity of spatial/anatomical errors" },
                frequencyAnomalies: { type: Type.NUMBER, description: "0-100 severity of noise/frequency artifacts" },
                compressionGhosting: { type: Type.NUMBER, description: "0-100 severity of compression artifacts" },
                metadataIntegrity: { type: Type.BOOLEAN, description: "True if metadata/headers look clean, False if stripped/suspicious" }
              },
              required: ["spatialInconsistencies", "frequencyAnomalies", "compressionGhosting", "metadataIntegrity"]
            },
            modelScores: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  name: { type: Type.STRING },
                  score: { type: Type.NUMBER, description: "0-100 score indicating probability of fake for this specific aspect." },
                  description: { type: Type.STRING },
                  weight: { type: Type.NUMBER }
                },
                required: ["name", "score", "description", "weight"]
              }
            }
          },
          required: ["verdict", "confidence", "explanation", "artifacts", "modelScores"]
        }
      }
    });

    const jsonText = response.text;
    if (!jsonText) {
      throw new Error("Empty response from analysis model.");
    }

    const data = JSON.parse(jsonText);
    const endTime = performance.now();

    return {
      id: crypto.randomUUID(),
      timestamp: new Date().toISOString(),
      filename: file.name,
      processingTimeMs: Math.round(endTime - startTime),
      verdict: data.verdict as Verdict,
      confidence: data.confidence,
      modelScores: data.modelScores,
      artifacts: data.artifacts,
      explanation: data.explanation
    };

  } catch (error) {
    console.error("Forensic analysis failed:", error);
    throw error;
  }
};